discord_bot_token: ENC[AES256_GCM,data:kmoaoA7TSiRSEjjUnY7x7o/HbtSD5t3J06/64cR6Ll7pouIPTzlBYbRHtaA7GNxsAVBbX706kAFbKuph5fkCusMw9XkhPEEp,iv:KC/fkATy1SGNIvUq8H35sMWw8eYSmRCofJsAnJ9xATA=,tag:hEXntt9PRImxgKtiPJ24jg==,type:str]
solidarity_tech_token: ENC[AES256_GCM,data:Ow5j+NSXGyCua1ww25E1OBqk5q4rlCDPged2Ms6a4tjdLhbqeaBmOQjn2HAsBZ6tggm+XhVzYO/H+xjK5ssKnlwXVZj4yH5S5n/M2UeCeCmq/sQ1LPo/dpbtWl3Kwt09H1cwUTolQVmPFUhw1S3JGleVxMkAqNFRV+sLTfHKwG4=,iv:KUVJa/qPr8vYRMCoU85UVrN1j+7xjcJXhv7Dja0s1cE=,tag:stsUQUQev02sJnbkS6gefQ==,type:str]
db_migration_password: ENC[AES256_GCM,data:GqhZxcvg4AapUgWCokpx7/N7YFuWEwoDr5N77Guh3l65WpZ9KdbFcb7oX4XUbmxLNjw=,iv:H7AN7VSoKxHhE71BVJL78FNsPzgzakyn1p0l/JHvBxY=,tag:7Inye1xaDEKTGToedpXdLA==,type:str]
b2_application_key: ENC[AES256_GCM,data:hkBBwaOD+OH09d3QnDwNi4RDGTWVhI+SlXErRxaPXg==,iv:Y5mEAhIkuDKNoXxhMETI0FFwVacRdERpZirEYt5K1hU=,tag:iBBmTTMEfd0VL1PjQGWlrQ==,type:str]
b2_key_id: ENC[AES256_GCM,data:CI27qjpITqAAulXJeAvv9YGOQmDNfqOmpw==,iv:/zKxwtU7BcPVeMwtVkPSBoHCP5O40NZ20yZCJ7XfqSE=,tag:x+E9okxig7Mkda4M8SqWeQ==,type:str]
b2_bucket_name: ENC[AES256_GCM,data:77dHP29hJZ0oHhCamis=,iv:1lHCrgoPprhZswufYROtwAuPt65uGkTybaWnXGYOgfg=,tag:pUPQ+DhshMaEycZmcHqKaQ==,type:str]
discord_guild_id: ENC[AES256_GCM,data:OYfqbP7xTe5NkhfGYbwhbtkHtA==,iv:z78NILvoGFftBSDb7zzfnThqftqSjafzvIAOBgqWUds=,tag:eVRTdP3/3Nkj6gFrlN94jg==,type:int]
discord_mod_id: ENC[AES256_GCM,data:BZG7klGVsW0bX8oieGgACt0HEg==,iv:0AUtf+BrGU+KMjtYQzpNaYomvQ0tMXKV4SjH+POl7dw=,tag:VVB91BjafCDWEMZu9qM0Nw==,type:int]
st_user_list_id: ENC[AES256_GCM,data:nbQKd3s=,iv:cQc2LAyW9r80FeVCZWbICFroCo2G0I0IAE16x16jnig=,tag:W7l4Q32vi9+8E1Hb4mr1Jg==,type:int]
box_age_pubkey: ENC[AES256_GCM,data:CZFKQ5K3YEVX3ay+DupAKYteig90GsSelKtZeVri/LEl0SVgXZR8mIvkRyAKdJ8aQHzagMekcfbvgSp0dgw=,iv:KNqFSy5CNtoJtgVCtJ5DQhqI6+00tJU5ybU5BPm5xSg=,tag:23OEJ6RrLfyr4Bec9qwpqQ==,type:str]
audit_hash_key: ENC[AES256_GCM,data:whAOgcPYGesN8WT0l3V+nyd6iTlFFylhHM+rrZrKNM1ECJxGBZ0Bg3SOvaRPlKz+zCuULYPLtrmI/N59hbDFug==,iv:HGwdwe0LSz30L3QJPujhXmyzDFe9ftE9Kr/R67syg+c=,tag:vUXAvYrkvOn9T0U5mlt+ig==,type:str]
sops:
    age:
        - recipient: age1wrk9tqsk9f5g258q3dla2utjpyeh5q9u28k8w97pn30gmu36cqnq959hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMkduVUdabnRsa0FaK3pK
            NEpuVCtETU1YNHIvMWIyVFhhU2laQWtHTGhjCmpHMGFwYXc2MGRmN0E5MmIwU3Bv
            OUFhQ0REYlB5djJHM2FNSHNxYlhjR00KLS0tIFE4dldVNHVoZ1phREVQeDYxQkxN
            azd1Y0c3TGJ5cHVacXdsU0J5OXZFNE0KzxN+NDcnZHsNsEMaJ2E/oqSQdv5EWqsF
            H4fvnOGEc5kDuruCcpOzJDre32Svevboe3j80j8/L/zBXmg4DlNWFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157h9dve7su6uguer30pexnhntgysqttsyd6umrutshkkzmpp9qnqlvuttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRSt4YVpISmtoYnpYWGht
            M3A4UzRqZGQzbWJwVFZvT092Q1V2cnVqY1FjCld1TFUvdi9VaGxVVytQVmx6NUZB
            ZWxkV2RzWGw2cG51K0d5aVZQNjBMQlEKLS0tIDFiOGtRTHUwTzFNWEducytSVlZZ
            bnpOSVFjclp6WHBvTUE5cFNPREhrb0UKVBr4vT6ein+/opPSyeoinMzklcUk1EQA
            i4D/7BiJ4CClXDSj7b7q9s0Wsu4Dsvhy+G7fPGZb5sNsnAxy9aYg0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T04:56:08Z"
    mac: ENC[AES256_GCM,data:TFpVrBYLBBUs80pl3VJ7432Uu8Xh5X69y6YWrbo0BUYCdbaIXbY0FjU6/vVapzOWbWYUoBT37greXiiMuK7NZYwxn7nngSaW7MeDtls+JOTfFus/YFgqzNr+UyNhrVU2HL1rAfqP9dHSCuEreQfGge+jjgs24f0W4nnKrBLg2Pg=,iv:ys94ZAUwF6paCbG1fg7tHGdn2vzVtFHX1GAN4Vmfrfk=,tag:jrCs5BC/8EhmzFrSTT1yoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
