discord_bot_token: ENC[AES256_GCM,data:kmoaoA7TSiRSEjjUnY7x7o/HbtSD5t3J06/64cR6Ll7pouIPTzlBYbRHtaA7GNxsAVBbX706kAFbKuph5fkCusMw9XkhPEEp,iv:KC/fkATy1SGNIvUq8H35sMWw8eYSmRCofJsAnJ9xATA=,tag:hEXntt9PRImxgKtiPJ24jg==,type:str]
solidarity_tech_token: ENC[AES256_GCM,data:Ow5j+NSXGyCua1ww25E1OBqk5q4rlCDPged2Ms6a4tjdLhbqeaBmOQjn2HAsBZ6tggm+XhVzYO/H+xjK5ssKnlwXVZj4yH5S5n/M2UeCeCmq/sQ1LPo/dpbtWl3Kwt09H1cwUTolQVmPFUhw1S3JGleVxMkAqNFRV+sLTfHKwG4=,iv:KUVJa/qPr8vYRMCoU85UVrN1j+7xjcJXhv7Dja0s1cE=,tag:stsUQUQev02sJnbkS6gefQ==,type:str]
db_migration_password: ENC[AES256_GCM,data:GqhZxcvg4AapUgWCokpx7/N7YFuWEwoDr5N77Guh3l65WpZ9KdbFcb7oX4XUbmxLNjw=,iv:H7AN7VSoKxHhE71BVJL78FNsPzgzakyn1p0l/JHvBxY=,tag:7Inye1xaDEKTGToedpXdLA==,type:str]
b2_application_key: ENC[AES256_GCM,data:hkBBwaOD+OH09d3QnDwNi4RDGTWVhI+SlXErRxaPXg==,iv:Y5mEAhIkuDKNoXxhMETI0FFwVacRdERpZirEYt5K1hU=,tag:iBBmTTMEfd0VL1PjQGWlrQ==,type:str]
b2_key_id: ENC[AES256_GCM,data:CI27qjpITqAAulXJeAvv9YGOQmDNfqOmpw==,iv:/zKxwtU7BcPVeMwtVkPSBoHCP5O40NZ20yZCJ7XfqSE=,tag:x+E9okxig7Mkda4M8SqWeQ==,type:str]
b2_bucket_name: ENC[AES256_GCM,data:77dHP29hJZ0oHhCamis=,iv:1lHCrgoPprhZswufYROtwAuPt65uGkTybaWnXGYOgfg=,tag:pUPQ+DhshMaEycZmcHqKaQ==,type:str]
sops:
    age:
        - recipient: age1wrk9tqsk9f5g258q3dla2utjpyeh5q9u28k8w97pn30gmu36cqnq959hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMkduVUdabnRsa0FaK3pK
            NEpuVCtETU1YNHIvMWIyVFhhU2laQWtHTGhjCmpHMGFwYXc2MGRmN0E5MmIwU3Bv
            OUFhQ0REYlB5djJHM2FNSHNxYlhjR00KLS0tIFE4dldVNHVoZ1phREVQeDYxQkxN
            azd1Y0c3TGJ5cHVacXdsU0J5OXZFNE0KzxN+NDcnZHsNsEMaJ2E/oqSQdv5EWqsF
            H4fvnOGEc5kDuruCcpOzJDre32Svevboe3j80j8/L/zBXmg4DlNWFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age157h9dve7su6uguer30pexnhntgysqttsyd6umrutshkkzmpp9qnqlvuttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRSt4YVpISmtoYnpYWGht
            M3A4UzRqZGQzbWJwVFZvT092Q1V2cnVqY1FjCld1TFUvdi9VaGxVVytQVmx6NUZB
            ZWxkV2RzWGw2cG51K0d5aVZQNjBMQlEKLS0tIDFiOGtRTHUwTzFNWEducytSVlZZ
            bnpOSVFjclp6WHBvTUE5cFNPREhrb0UKVBr4vT6ein+/opPSyeoinMzklcUk1EQA
            i4D/7BiJ4CClXDSj7b7q9s0Wsu4Dsvhy+G7fPGZb5sNsnAxy9aYg0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T19:39:22Z"
    mac: ENC[AES256_GCM,data:tN7KdrZrWbxDA4JHDg6d6IGFAq1LI3TIYWz6O8EjTxyZLrAzwh60F2uzhoKiF4HFholSZFtEHuNEL07OsQqv+9rfgnV0FlLbYLdEIjVOCuawIADvWwdL3lXrhND/xToD0LwU0e5sdu+agSbTVxmFrVUzOScneUWDiXqh3ApPUzk=,iv:uglT2CFdmSSJ4ARNAbRrSdEYhclu38SwRAJcJfnlUKI=,tag:S6wKuCF2zl+sf02a+zdOBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
